# Generated by Django 4.2.3 on 2025-10-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_is_active"),
        ("shortner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name="shorturl",
            unique_together={("organization", "slug")},
        ),
    ]
